### ISSUE TITLE
migrate solo -> para using incremental setStorage

### ISSUE THREAD

**Issue by brenzi** [integritee-network/parachain#76]
As the seedling approach won't be available soon #62, we need to do it with a more manual process:

centrifuge approach (successfully tested with their Kusama parachain, not yet Polkadot):
* readme: https://centrifuge.hackmd.io/HpGW0J6TRo25splXkuH9TA?view
* `centrifuge-cli` typescript tool: https://github.com/centrifuge/centrifuge-cli/tree/main/packages/plugins/migration
* presentation with some background info: https://www.youtube.com/watch?v=sIgvyRFs-N4
* Migration pallet: https://github.com/centrifuge/centrifuge-chain/blob/parachain/pallets/migration/src/lib.rs

The basic flow:

* [x] update para and solo runtime to be based on same substrate commit (a polkadot-release commit). 
    * [x] para runtime should filter extrinsics and only allow sudo
* [x] upgrade solochain to a filtered runtime (no more extrinsics can happen, "downtime" starts for withdrawals and depoits at exchanges)
* [x] migration script will read all keys from solo and call `sudo.setStorage` on para, while it has to translate vesting schedules because block numbers can't be aligned
* [x] shut down public api's for solo -> replaced with para api's
* [x] lift extrinsic filters on parachain -> process finished 🏁 

semi-dry run is possible against productive solo by just letting it run and migrating it to a local para. inconsistencies may occur, but basic functionality can be tested

specialties:
* need to auto-migrate at least `balances`, `vesting`, `claims`, (maybe needed, check:  `proxy`, `multisigs`, `scheduler`)
* no strict need to migrate `teerex`, and  `teeracle` as we can easily re-register these.

consider:
* in order to accelerate the tons of rpc requests, we may want to run a solo and para node on the same machine and run the migration locally

**Comment by haerdib** [comment]
Closing this epic, as the migration has been successfully enacted (https://github.com/integritee-network/parachain/issues/81 resp. https://github.com/integritee-network/deployment/issues/54)
