### ISSUE TITLE
HRMP with Acala

### ISSUE THREAD

**Issue by brenzi** [integritee-network/parachain#97]
We plan to open an HRMP channel for the purpose of token transfers between the respective Kusama chains.

Instructions from Acala team: https://wiki.acala.network/build/development-guide/composable-chains/open-hrmp-channel

* [x] test HRMP in rococo-local setup using an instance of Karura and Integritee collators
* [x] test on Live Rococo together with Acala Team **target: April 25th**
* [x] propose to open an HRMP channel on Kusama establish token transfer

**Comment by haerdib** [comment]
Has been successfully established. Closing this
